### ISSUE TITLE
mdb-schema sqlite backend  Constraint not supported by sqlite 

### ISSUE THREAD

**Issue by marcobra** [mdbtools/mdbtools#134] opened 2018-03-24 16:49 UTC
mdb-schema  mydb.mdb sqlite

...
-- CREATE Relationships ...
ALTER TABLE `PRATICHE_AMMPUB` ADD CONSTRAINT ... 
...

Since contraint isn't supported by sqlite 

https://stackoverflow.com/questions/1884818/how-do-i-add-a-foreign-key-to-an-existing-sqlite-table

can mdb-schema solve this issue by adding some better instruction at table creation code ?

Thank you

**Comment by evanmiller** [comment] 2020-08-05 22:43
Duplicate of #82

**Closed** 2020-09-02 01:00 UTC
