### ISSUE TITLE
RFE: libmdbsql should not call exit

### ISSUE THREAD

**Issue by jwrdegoede** [mdbtools/mdbtools#314] opened 2021-07-09 16:02 UTC
I'm working on updating the Fedora packages to mdbtools-0.9.z (thank you for reviving the project), while doing this I ran rpmlint on the generated rpms and it gave this warning:

```
mdbtools-libs.x86_64: W: shared-lib-calls-exit /usr/lib64/libmdbsql.so.3.0.3 exit@GLIBC_2.2.5
```

The reason that it complains here is because it is considered undesirable for libraries used by programs to cause the entire program to exit on an error.

**Comment by pedromorgan** [comment] 2021-07-09 21:51
So if ok.  just tagged as a BUG, as I can understand this issue.. from another project with similar scenario..

**Comment by evanmiller** [comment] 2021-08-05 13:54
Duplicate of #181. This exit is generated by Yacc and is difficult to work around.

**Comment by jwrdegoede** [comment] 2021-08-05 14:02
> Duplicate of #181. This exit is generated by Yacc and is difficult to work around.

Ok, so lets mark this as such then (it seems github did not pick up your duplicate marking, so let me retry with nothing else on the magic line).

**Comment by jwrdegoede** [comment] 2021-08-05 14:02
Duplicate of #181

**Closed** 2021-08-05 14:05 UTC
Labels: bug, enhancement
