### ISSUE TITLE
postgres insert column doesn't exist

### ISSUE THREAD

**Issue by shorabhd** [mdbtools/mdbtools#128] opened 2018-02-02 00:19 UTC
I am converting a accdb file to sql file using mdbtools export tables. For insert queries it is generating something like this:

INSERT INTO TABLE_NAME ("COLUMN1", "COLUMN2") VALUES ("ABC", "DEF");

I am getting column doesn't exist on "ABC" since it is in double quotes instead of single quotes.

**Comment by akaspick** [comment] 2020-02-20 12:27
Use `mdb-export -q "'" -X "'" -I postgres db.mdb`

**Comment by evanmiller** [comment] 2020-08-05 22:21
This is a duplicate of #119

**Closed** 2020-09-02 01:37 UTC
